FROM node:alpine

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
COPY ./prisma prisma

RUN npm install --silent
RUN npx prisma migrate dev --name init

COPY . .

RUN chown -R node /app/node_modules

USER node
CMD ["npm", "run", "dev"]
