services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    links:
      - db:database
    volumes:
      - /app/node_modules
      - .:/app/
    ports:
      - "3000:3000"
    tty: true
    user: 1000:1000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - prisma_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=prisma

volumes:
  prisma_data:
    driver: local
