services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - .:/usr/app/
    ports:
      - "3000:3000"
    tty: true
    user: 1000:1000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
    driver: local
  postgres_keycloak:
    driver: local

networks:
  keycloak-network:
    driver: bridge
